# Generated by Django 6.0 on 2026-08-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_reward_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
