# Generated by Django 6.0 on 2026-08-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_pendingcheckout'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancellation_requested', 'Cancellation Requested'), ('cancellation_approved', 'Cancellation Approved'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending_payment', max_length=30),
        ),
    ]
