# Generated by Django 6.0 on 2026-08-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('delivery', 'Delivery'), ('cancellation_requested', 'Cancellation Requested'), ('cancellation_approved', 'Cancellation Approved'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending_payment', max_length=30),
        ),
    ]
