# Generated by Django 6.0 on 2025-12-26 08:20

import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sneaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(choices=[('nike', 'Nike'), ('adidas', 'Adidas'), ('jordan', 'Jordan'), ('puma', 'Puma'), ('new_balance', 'New Balance'), ('reebok', 'Reebok'), ('converse', 'Converse'), ('vans', 'Vans'), ('balenciaga', 'Balenciaga'), ('gucci', 'Gucci'), ('other', 'Other')], max_length=50)),
                ('category', models.CharField(choices=[('running', 'Running'), ('basketball', 'Basketball'), ('lifestyle', 'Lifestyle'), ('training', 'Training'), ('skateboarding', 'Skateboarding'), ('soccer', 'Soccer'), ('boots', 'Boots'), ('customs', 'Customs')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('copies', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('img1', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('img2', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('img3', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=200)),
                ('sizes', models.CharField(choices=[('5', 'US 5'), ('5.5', 'US 5.5'), ('6', 'US 6'), ('6.5', 'US 6.5'), ('7', 'US 7'), ('7.5', 'US 7.5'), ('8', 'US 8'), ('8.5', 'US 8.5'), ('9', 'US 9'), ('9.5', 'US 9.5'), ('10', 'US 10'), ('10.5', 'US 10.5'), ('11', 'US 11'), ('11.5', 'US 11.5'), ('12', 'US 12'), ('13', 'US 13')], max_length=10)),
                ('available_sizes', models.JSONField(default=list, help_text='List of available sizes in JSON format like ["8", "9", "10"]')),
                ('features', models.JSONField(default=list, help_text='List of feature tags like ["best_seller", "featured"]')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
