# Generated by Django 6.0 on 2026-02-14 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sneaker',
            name='sizes',
        ),
    ]
