# Generated by Django 6.0 on 2026-08-14 06:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, choices=[('5', 'US 5'), ('5.5', 'US 5.5'), ('6', 'US 6'), ('6.5', 'US 6.5'), ('7', 'US 7'), ('7.5', 'US 7.5'), ('8', 'US 8'), ('8.5', 'US 8.5'), ('9', 'US 9'), ('9.5', 'US 9.5'), ('10', 'US 10'), ('10.5', 'US 10.5'), ('11', 'US 11'), ('11.5', 'US 11.5'), ('12', 'US 12'), ('13', 'US 13')], help_text='Selected US size for this cart line', max_length=10, null=True)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sneaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_carts', to='products.sneaker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'sneaker', 'size')},
            },
        ),
    ]
