# Generated by Django 5.2.12 on 2026-08-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="sneaker",
            name="silhouette",
            field=models.CharField(
                blank=True,
                choices=[("low", "Low Top"), ("mid", "Mid Top"), ("high", "High Top")],
                help_text="Silhouette: low / mid / high top",
                max_length=10,
                null=True,
            ),
        ),
    ]
